# Generated by Django 4.0.2 on 2022-02-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='food_group',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Fruit', 'Fruit'), ('Grain', 'Grain'), ('Protein', 'Protein'), ('Dairy', 'Dairy'), ('Confectionery', 'Confectionery'), ('Unknown', 'Unknown')], default='Unknown', max_length=100),
        ),
    ]
